spring:
  application:
    name: backend
  data:
    redis:
      host: localhost
      port: 6379

auth:
  cookie:
    refresh:
      name: refreshToken
      path: /api/v1/auth
      same-site: Lax
      secure: true

app:
  fcm:
    enabled: false

