spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:55432/builders
    username: builders
    password: builders123
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  access-secret: your-very-long-random-secret-key
  refresh-secret: your-very-long-random-refresh-secret-key
  access-ttl-sec: 1800
  refresh-ttl-sec: 1209600

app:
  upload-dir: uploads
